kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-rolebinding
  namespace: devops-tools
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: devops-tools
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
