kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops-tools
  name: jenkins-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments", "services", "pods", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
